"""empty message

Revision ID: 6fc5a30b71ba
Revises: 
Create Date: 2023-03-11 20:05:36.577446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc5a30b71ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gm',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('numReviews', sa.Integer(), nullable=True),
    sa.Column('lookUpRequests', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gm')
    # ### end Alembic commands ###
