"""empty message

Revision ID: e1376489eaea
Revises: 6fc5a30b71ba
Create Date: 2023-03-11 20:36:11.147654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1376489eaea'
down_revision = '6fc5a30b71ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gm', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
